### ISSUE TITLE
How to make this work with Square's Spoon

### ISSUE THREAD

**Issue by eric-grab** [bitrise-steplib/steps-virtual-device-testing-for-android#11]
Note that I'm using a Gradle plugin to run instrumentation tests with Spoon so it's only a matter of:

- Replacing the Gradle task that runs the tests with ./gradlew spoon (I’m using a Gradle plugin; this runs the tests + generate reports)
- Copy the reports in “./app/build/spoon-outputs/” to “Apps & Artifacts”

Could you help @trapacska ?

**Comment by trapacska** [comment]
Hey @eric-grab!

Just answered on the discuss topic, please see here: https://discuss.bitrise.io/t/how-to-run-android-ui-tests-on-virtual-devices/2496/27

Just closing this issue as it is not an issue with the step itself.

Thanks!
