### ISSUE TITLE
How to run Espresso for a particular variant

### ISSUE THREAD

**Issue by eric-grab** [bitrise-steplib/steps-virtual-device-testing-for-android#12]
is there anyway I could choose to run `./gradlew connectedSomeVariantAndroidTest` instead of `./gradlew connectedAndroidTest`?

**Comment by trapacska** [comment]
Hey @eric-grab !

AFAIK if you generate the app apk, and the test apk like `assembleSomeVariant` and `assembleSomeVariantAndroidTest` instead of `assemble` and `assembleAndroidTest` then it should contain the desired test and app details.

**Comment by trapacska** [comment]
I close this issue now, as it is not an issue with the step itself. Please write your questions on our http://discuss.bitrise.io site to get the best feedbacks asap.

Thank you!
