### ISSUE TITLE
Cannot use device location (Google Play Services : maps)

### ISSUE THREAD

**Issue by Aissa-H** [bitrise-steplib/steps-virtual-device-testing-for-android#13]
Hi @trapacska, thank you a lot for this step, it will significantly improve my CI workflow! :+1: 

I tried a test which needs the location of the device. In the code of the app, I use the `FusedLocationProviderClient` class provided by the Google Location API. I also use a `GoogleMap` object to display the map in my fragment.

Unfortunately, neither the retrieving of the location nor the map are working as I can see in the video result.

Coarse, on the top on my test, I use a permission rule to allow the location permission as follow:
```java
@Rule public GrantPermissionRule grantPermissionRule =
      GrantPermissionRule.grant(Manifest.permission.ACCESS_FINE_LOCATION);
```

The tests runs correctly on real devices.

I think this is maybe a problem of installation of Google Play Services on the virtual devices, what do you think?

Thank you in advance! :v:

**Comment by trapacska** [comment]
Hey @Aissa-H! 👋

As far as I know, on emulator you will need to use mock/test provider.

Here is an example: https://stackoverflow.com/questions/1972895/testing-gps-in-android/3940877#3940877
