### ISSUE TITLE
What is the APIBaseURL in Bitrise's New Android Virtual Device Testing

### ISSUE THREAD

**Issue by nicholas-jomo** [bitrise-steplib/steps-virtual-device-testing-for-android#2]
Original link: https://stackoverflow.com/questions/46532886/what-is-the-apibaseurl-in-bitrises-new-android-virtual-device-testing

The article above doesn't mention anything related to APIBaseURL... the instrumentation test would result in:

[Issue with APIBaseURL: parameter not specified]

Anyone has any idea what the APIBaseURL means?

**Comment by trapacska** [comment]
Hey @nicholas-jomo !

I've answered it already on stackoverflow. Please feel free if the solution there is not fixed the issue!
🚀

**Comment by adridevparis** [comment]
Hi,
I'm facing the same issue.
I tried turning off and on the setting option, removing and adding again the android test option, without any success.
What could I provide you to help investing this issue further ?

Thanks in advance for your answer :)
Adrien

**Comment by trapacska** [comment]
Hey @adridevparis !

I will need info about the build and and the app as well. Please contact us on our on-site chat with your build log's url!

Thanks 🚀

**Comment by trapacska** [comment]
@adridevparis: at the same time we've found and resolved an issue in the website. Please turn off and on back again, it should work absolutely fine now!

Closing the issue for now as it seems to be fixed so far, but please feel free to re-open if you encounter any issues again! 😊

🚀🎉
