### ISSUE TITLE
Are my tests running or is reporting broken?

### ISSUE THREAD

**Issue by eric-grab** [bitrise-steplib/steps-virtual-device-testing-for-android#21]
Hi there, I have 22 Espresso tests recently.
However, there is something weird with the report recently.
Do you know what's wrong or how to troubleshoot this?
![screen shot 2018-05-07 at 11 53 20 am](https://user-images.githubusercontent.com/31608374/39684336-bec30342-51ed-11e8-81ed-973a14b651cc.png)
![screen shot 2018-05-07 at 11 52 33 am](https://user-images.githubusercontent.com/31608374/39684337-bf00cf10-51ed-11e8-83a3-76c37a00bac2.png)

Version: 1.0.2

**Comment by trapacska** [comment]
Hey @eric-grab ! 

What is the issue? For me it seems ok. You have run tests on one device. If you click on the device you will be able to see the test cases(hopefully all 22)

Not that is the case?

**Comment by godrei** [comment]
Closing as we did not receive a reply - @eric-grab please let us know if we can help with anything and we'll reopen this issue!
