### ISSUE TITLE
Disable animation while running Espresso tests

### ISSUE THREAD

**Issue by CoreFloDev** [bitrise-steplib/steps-virtual-device-testing-for-android#25]
Hi,

We are using this emulator to run Android Espresso tests on Bitrise. One of the requirement to avoid flaky tests, is to disable animations on the device as specified in the documentation https://developer.android.com/training/testing/espresso/setup

Unfortunately, it seems that there is no option to disable animations. Is it possible to add a parameter to disable them? Or maybe I am just missing something?

To disable the animation, this command work well:
```
adb shell settings put global window_animation_scale 0
adb shell settings put global transition_animation_scale 0
adb shell settings put global animator_duration_scale 0
```

Please tell me if you need more details

Thanks!

**Comment by bitce** [comment]
Hi @CoreFloDev ! Indeed, animations are not off by default, and you may run the exact script you mentioned in a Script step to disable them! 

Or are you meaning to submit this to us as a [feature request](https://discuss.bitrise.io/c/feature-request), the include this option in the step by default? :)

**Comment by shendriksen** [comment]
Hi Bitce,

We are using the '[BETA] Virtual Device Testing for Android' step on Bitrise.

This step bring up an emulator, runs the tests and destroys the emulator.

Our problem is that we cannot place a step before or after this step to disable animations as the emulator will not exist during those times.

Ideally it would be nice to setup hooks on the Virtual Device step so that we can run the above adb commands when the emulator is created. Alternatively an option to disable animations would be nice.

**Comment by bitce** [comment]
Hey @shendriksen,

Sorry, should have clarified first that in order to do this you need the [Android Debug Bridge](https://developer.android.com/studio/command-line/adb), as this would allow you to connect to the device in the meantime and run the adb commands.

**Comment by shendriksen** [comment]
@bitce we are currently using the following steps:

![image](https://user-images.githubusercontent.com/23698167/43589499-c40f92f8-9666-11e8-8cf0-ba059409e2b0.png)

We would like to use ADB as you mention but putting a script with the below before or after '[BETA] Virtual Device Testing for Android' will not work.

`adb shell settings put global window_animation_scale 0
adb shell settings put global transition_animation_scale 0
adb shell settings put global animator_duration_scale 0`

Do you have an example of what you are suggesting please?

Thanks

**Comment by times-tools** [comment]
Thanks @bitce.

I have opened a feature request for the ability to run scripts after the device has booted:
https://discuss.bitrise.io/t/beta-virtual-device-testing-for-android-custom-adb-script-option/5813

**Comment by shendriksen** [comment]
Thanks @bitce.

I have opened a feature request for the ability to run scripts after the device has booted:
https://discuss.bitrise.io/t/beta-virtual-device-testing-for-android-custom-adb-script-option/5813

**Comment by bitce** [comment]
Sure thing! 

I'm glad to hear that! We'll get back to you there too 😉

**Comment by CoreFloDev** [comment]
I don't use Bitrise on my new projects so no
