### ISSUE TITLE
Any plans to support physical devices

### ISSUE THREAD

**Issue by tir38** [bitrise-steplib/steps-virtual-device-testing-for-android#27]
There are a boat load more physical devices on Firebase than AVDs. Any plan to support some or all of these? I know it'll cost more but I'm sure there are some teams who would pay for this feature =)

**Comment by bitce** [comment]
Hi @tir38 !

Could you please create a [feature-request](https://discuss.bitrise.io/c/feature-request) about this?
Based on the number of votes it receives, we'll definitely discuss it! 🙂

**Comment by tir38** [comment]
Thanks. Done: https://discuss.bitrise.io/t/firebase-close-testing-support-physical-devices/6081
