### ISSUE TITLE
Add clearPackageData flag

### ISSUE THREAD

**Issue by PaulWoitaschek** [bitrise-steplib/steps-virtual-device-testing-for-android#29]
When running my instrumentation tests, I don't want shared state between executions.
So I add the flag 
`--environment-variables clearPackageData=true'`

I really need this for my tests to pass, how can I achieve it using this build step?

**Comment by trapacska** [comment]
Hey @PaulWoitaschek !

The step has an input for environment variables, did you try to input that in there?

**Comment by guness** [comment]
hey, what about enabling orchestrator?

**Comment by godrei** [comment]
I'll close this issue, but if you need more info/help open a new issue!
