### ISSUE TITLE
How do I set the parameters of the test-runner in Bitrise?

### ISSUE THREAD

**Issue by cnevinc** [bitrise-steplib/steps-virtual-device-testing-for-android#35]
I want to set up the parameter for test runners. i.e. testInstrumentationRunnerArguments

I know there's a way to set the test-runner class(testInstrumentationRunner)  using inst_test_runner_class. But how do I set the parameters of the test-runner?

**Comment by lszucs** [comment]
Hi @cnevinc,

If I'm not mistaken, you are talking about passing the parameters specific to `am instrument`, right? (https://developer.android.com/studio/test/command-line#AMOptionsSyntax)

You can pass these options to the test runner using the step's input variables.

Some parameters are exposed directly (e.g.: package id), some of them through the environment_variables (e.g.: coverage file) input.

The environment_variables field corresponds to the gcloud client's --environment-variables flag (see: https://cloud.google.com/sdk/gcloud/reference/firebase/test/android/run), you should be able to define the options accordingly.

**Comment by lszucs** [comment]
Hi @cnevinc,

Did you manage to move forward with your issue? Is there anything I can you help you with or may I close this issue?
