### ISSUE TITLE
Stability issues

### ISSUE THREAD

**Issue by glureau-betclic** [bitrise-steplib/steps-virtual-device-testing-for-android#39]
When starting multiple times the same automation tests, I sometimes got errors related to Firebase (as far as I understand):

```
Upload APKs
Failed to start test: 500, error: {"error":"Internal error"}
```

and sometimes I got this one:

```
Waiting for test results
- Validating
- (4/4) running
Failed to get test status, error: 
<h1>We're Sorry!</h1>
<p>
It looks like something went wrong! Don't worry, we are aware of the problem and are looking into it.
</p>
<p>
Sorry if this has caused you any problems. Please check back again later.
</p>
```

I understand that Firebase cannot deliver 100% uptime, but I'd love to have a flaky/retry option so when this kind of error is produced the steps automatically retry (maybe after a delay).

(Also if you have any kind of workaround, please share, thanks :) )

**Comment by bitce** [comment]
Hi @glureau-betclic!

Unfortunately, these issues kept on happening for a lot of us, from what we've seen this affected everyone using the Test Lab regardless of Bitrise. 

Thankfully we're receiving fewer reports so we are hoping this means that the service is a lot more stable.  You do raise a good point about the retry option, feel free to create a feature request about it here: https://discuss.bitrise.io/c/feature-request

**Comment by glureau-betclic** [comment]
Hi @bitce 
Thanks for the response, and good to hear we're not alone with this issue :)

I'm closing this ticket: I created a feature request as you suggested: https://discuss.bitrise.io/t/retry-mechanism-on-tasks/8456
Looks like there is already work in progress on retry mechanism...
