### ISSUE TITLE
Question: Is this task running tests in series for multiple devices?

### ISSUE THREAD

**Issue by tir38** [bitrise-steplib/steps-virtual-device-testing-for-android#40]
If I run a set of tests on two separate devices, do these run in parallel or series? My initial impression is that this task is waiting for one set of tests to complete before starting another emulator on FTL and starting tests on that second device.

**Comment by fehersanyi-bitrise** [comment]
Hello there!

As far as I know it runs parallel.

**Comment by tir38** [comment]
Ok, looking at logs in my tests I see they are running at the same time. Thanks.
