### ISSUE TITLE
APKs Failed to start test: 403, error: {"error":"Unauthorized request"}

### ISSUE THREAD

**Issue by hernandazevedozup** [bitrise-steplib/steps-virtual-device-testing-for-android#44]
I'm getting this error when I try to upload the apk to the virtual device testing:

APKs Failed to start test: 403, error: {"error":"Unauthorized request"}

**Comment by georgehadly-marleyspoon** [comment]
I have the same issue, 2 hours ago everything was working fine.

**Comment by luismfonseca** [comment]
Apparently they have updated the status page with this: https://status.bitrise.io/incidents/wkzb8ftc5fbp

**Comment by tamasbazs** [comment]
Hi @hernandazevedozup, @georgehadly-marleyspoon, @luismfonseca 
Thanks so much for the report. We’re really sorry to be holding you up today! 😞 Please know that our Website team is aware of this issue and they are currently validating a fix for the issue. We will send you a follow-up message here as soon as it's resolved. Thank you for your patience! 🙌

**Comment by AdamGrzybkowski** [comment]
@tamasbazs any update on this?

**Comment by bitce** [comment]
HI @AdamGrzybkowski! This was an incident that was solved within a matter of hours, the same issue is definitely not persistent since then. If you're experiencing this error and unsure why, please contact us on our on-site chat or via e-mail at letsconnect@bitrise.io!

**Comment by lpusok** [comment]
Closing as issue was resolved.
