### ISSUE TITLE
Set gcloud --timeout

### ISSUE THREAD

**Issue by tir38** [bitrise-steplib/steps-virtual-device-testing-for-android#46]
Our tests are now taking longer than the default 15 minutes. Can you expose a way to set gcloud's `--timeout` argument? https://cloud.google.com/sdk/gcloud/reference/firebase/test/android/run#--timeout

**Comment by bitce** [comment]
Hi @tir38!

Could you send us a build URL of what you're experiencing exactly? As far as I know the timeout limit should be 45 minutes, this was very recently changed from 60 minutes.

**Comment by tir38** [comment]
Ahh maybe I was mistaken. I can't seem to find the build that triggered this for me.
