### ISSUE TITLE
(re)name log files to match test name

### ISSUE THREAD

**Issue by tir38** [bitrise-steplib/steps-virtual-device-testing-for-android#48]
Currently all of our log files are numbered. It makes it really difficult to find a log for a specific test. I'm not sure if these logs are split / named by Firebase or if this Bitrise step is doing that. It would be nice if these files could be named or renamed for each test method name.

<img width="526" alt="Screen Shot 2019-06-24 at 6 50 49 PM" src="https://user-images.githubusercontent.com/1980553/60367256-c8e69700-99bb-11e9-95e2-0a1990afd693.png">

**Comment by bitce** [comment]
Hi @tir38, that's actually a superb idea! Would you consider creating a feature request about this on our [Discuss](https://discuss.bitrise.io/c/feature-request)? 🙂

**Comment by tir38** [comment]
👍 https://discuss.bitrise.io/t/re-name-log-files-to-match-test-name/9558
