### ISSUE TITLE
Failed to get test status, error: Failed to get test status: INVALID(NO_TEST_RUNNER_CLASS

### ISSUE THREAD

**Issue by hafsalrahman** [bitrise-steplib/steps-virtual-device-testing-for-android#51]
I'm running Espresso with cucumber in my android project and getting an error as below,
```
Waiting for test results

Validating
Failed to get test status, error: Failed to get test status: INVALID(NO_TEST_RUNNER_CLASS)
```
build URL for your reference
https://app.bitrise.io/build/49803be5438de523
Also, I've enabled the support user.

**Comment by Roland-Bak** [comment]
Hi @hafsalrahman!

Could you try going to your build's workflow and delete the field for 'Test runner class', inside the [Beta] Virtual Device Testing step?
Android Build for UI Testing should take care of this for you, rebuilding with the 'Test runner class' as empty should do the trick! 🙂

**Comment by hafsalrahman** [comment]
It was solved when I used the step 'Android Build for UI testing'.
