### ISSUE TITLE
Max Timeout is set to 1800s when Firebase Test Lab allows for a maximum of 3600

### ISSUE THREAD

**Issue by gpowell13** [bitrise-steplib/steps-virtual-device-testing-for-android#59]
This commit changed the max timeout from allowing 3600 to allow 1800. https://github.com/bitrise-steplib/steps-virtual-device-testing-for-android/commit/d117c3e4a3b9f1ff194aa7b1ed5e18328d24519b

Firebase test lab allows a larger max timeout for Virtual Devices (3600).
https://cloud.google.com/sdk/gcloud/reference/beta/firebase/test/android/run#--timeout

Can you allow for 3600 to be set for the timeout, if the test is using virtual devices?

**Comment by gpowell13** [comment]
I was able to use an older version (1.0.5) of this step and could successfully run our tests with 3600 set as the max timeout.

**Comment by Roland-Bak** [comment]
Hi there @gpowell13 , just wanted to let you know we are aware of this, and are investigating! ;)
Will get back to you once there is progress :)

**Comment by gpowell13** [comment]
> Hi there @gpowell13 , just wanted to let you know we are aware of this, and are investigating! ;)
> Will get back to you once there is progress :)

Thanks for the quick response.

**Comment by glureau-betclic** [comment]
Hi there @Roland-Bak ,
Do you have some news on this topic?

**Comment by Roland-Bak** [comment]
Hey there @glureau-betclic, in fact I do! 🙂
Although no definite changes have been made, this is currently under estimation to be updated in the near future, and we'll get back to you once this implementation has been done 😉

**Comment by glureau-betclic** [comment]
I've created the PR, it's working fine on my side, but no test added.
@Roland-Bak Tell me in the PR if you want me to add tests or anything.

**Comment by glureau-betclic** [comment]
This should be solved now, right?

https://github.com/bitrise-steplib/steps-virtual-device-testing-for-android/commit/02a4aaf447177ea130e0a1b335361d4d0d29c6d5

**Comment by ofalvai** [comment]
Yes, this was solved in v1.1.2, I'm closing this issue. (let us know if you have other problems by opening a separate issue)
