### ISSUE TITLE
Failed to get test status: INVALID(TEST_SAME_AS_APP)

### ISSUE THREAD

**Issue by hitesh-banknovo** [bitrise-steplib/steps-virtual-device-testing-for-android#62]
I try to configure autorun Android Instrument test cases and export the test result into GIT tag but I got the error "**Failed to get test status: INVALID(TEST_SAME_AS_APP)**" in step "**virtual-device-testing-for-android**"

Error log:

> Uploading app and test files
> => Files uploaded
> Starting test
> => Test started
> Waiting for test results
> - Validating
> Failed to get test status, error: Failed to get test status: INVALID(TEST_SAME_AS_APP)
> |                                                                              |
> +---+---------------------------------------------------------------+----------+
> | x | virtual-device-testing-for-android@1.1.1 (exit code: 1)       | 17.13 sec|
> +---+---------------------------------------------------------------+----------+
> | Issue tracker: ...se-steplib/steps-virtual-device-testing-for-android/issues |
> | Source: ...thub.com/bitrise-steplib/steps-virtual-device-testing-for-android |
> +---+---------------------------------------------------------------+----------+

Workflow link: **https://app.bitrise.io/build/f2d9ba3e8f614ab5#?tab=log**

**Comment by hitesh-banknovo** [comment]
This error due to I configured the same apk path for the "App path" and "Test app path". It must be different and the issue is resolved.

![Bitrise Workflow editor](https://user-images.githubusercontent.com/51733544/72970030-ba931900-3dec-11ea-85af-55da832eb019.png)

**Comment by non-binary** [comment]
Great to hear! We're here to help if you need anything else.
