### ISSUE TITLE
Instrumentation failing for android

### ISSUE THREAD

**Issue by othiagosouto** [bitrise-steplib/steps-virtual-device-testing-for-android#66]
Hi,

I was trying to setup my instrumentation and following the steps provided [here](https://devcenter.bitrise.io/testing/device-testing-for-android/#running-instrumentation-tests), however, seems that it's not working as expected.

This is the log:

```

+------------------------------------------------------------------------------+
| (8) virtual-device-testing-for-android@1                                     |
+------------------------------------------------------------------------------+
| id: virtual-device-testing-for-android                                       |
| version: 1.1.2                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2020-05-18T01:37:31Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |

[34;1mConfigs:[0m
- AppPath: /bitrise/deploy/app-debug.apk
- TestTimeout: 900.000000
- FlakyTestAttempts: 0
- DownloadTestResults: false
- DirectoriesToPull: 
- AutoGoogleLogin: false
- EnvironmentVariables: 
- ObbFilesList: 
- TestDevices:
---
Model    API Level   Locale   Orientation   
Pixel2   28          en       portrait      
---
- TestType: instrumentation
- TestApkPath: /bitrise/deploy/app-debug-androidTest.apk
- InstTestPackageID: 
- InstTestRunnerClass: androidx.test.runner.AndroidJUnitRunner
- InstTestTargets: 
- UseOrchestrator: false

[34;1mUploading app and test files[0m
[32;1m=> Files uploaded[0m

[34;1mStarting test[0m
[32;1m=> Test started[0m

[34;1mWaiting for test results[0m
- Validating
- (1/1) running
- (0/1) running
[32;1m=> Test finished[0m

[34;1mTest results:[0m
Model    API Level   Locale   Orientation   Outcome              
Pixel2   28          en       portrait      [31;1mfailure[0m   
|                                                                              |
+---+---------------------------------------------------------------+----------+
| [31;1mx[0m | [31;1mvirtual-device-testing-for-android@1 (exit code: 1)[0m           | 3.4 min  |
+---+---------------------------------------------------------------+----------+
| Issue tracker: ...se-steplib/steps-virtual-device-testing-for-android/issues |
| Source: ...thub.com/bitrise-steplib/steps-virtual-device-testing-for-android |
+---+---------------------------------------------------------------+----------+


```

Workflow:
![image](https://user-images.githubusercontent.com/5900020/82168503-4ac20600-9895-11ea-934c-234abd2a81df.png)

Someone have any idea how to solve this or get more info about what it's causing this issue?

**Comment by Roland-Bak** [comment]
Hi there!

The cause of why Instrumentation Test issues fail can vary greatly, and it is possible that you have very different reasons for failing.
To keep it simple and to be able to focus in each of your issues individually, could you please submit a Support Ticket at our site? Please include the URL of a related build and enable Support Access (https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) so that we may investigate in detail? 🙂

Thanks!

**Comment by cchierici** [comment]
I also regularly run into the same issue, and yes, i know that instrumentation tests tend to be flaky, but i wonder if it's possible to get more log information to see where the test exactly has failed

**Comment by cathyharmon** [comment]
Hello,

The step has a couple of inputs you might want to check into.  If you click on "DEBUG", you will see various options.  You can set test timeouts and retries to help determine if it is a timing issue or if it was a temporary issue that resolves with a retry.

If there is specific output from a test, you can add the directory where the output is stored to have that information downloaded.

Finally, there is a Verbose log that can be set to true to enable verbose level logging.

If you include the Deploy to bitrise.io step, you can also check the [Test Reports ](https://devcenter.bitrise.io/testing/test-reports/)using the Test reports Add-on.  This can often provide additional information, logs, etc from the test and can help in determining the reason for the failure.

Thanks,
cathy

**Comment by Madonahs** [comment]
@othiagosouto  Not sure if you solved this, I wanted to share what worked for me. I checked the Test reports as @cathyharmon mentioned and saw the error (tests that actually failed), and had to handle the `idlingResources` and that fixed the error. Hope this helps. It now works well.
